version: '3.9'
services:
  go_backend:
    container_name: go_backend
    image: go_backend:local
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 1337:1337
    volumes:
      - ${PWD}/:/app
